
# Project ID is at the top to ensure it's not accidentally deleted
project_id = "zahnqwnyoezdnuccryqm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.vehicle-lookup]
verify_jwt = true
