
import { Vehicle, ServiceLog } from './mockData';

export const printServiceHistory = (vehicle: Vehicle, serviceLogs: ServiceLog[]) => {
  // Create printable section if it doesn't exist
  let printSection = document.querySelector('.print-section');
  
  if (!printSection) {
    printSection = document.createElement('div');
    printSection.classList.add('print-section');
    document.body.appendChild(printSection);
  } else {
    printSection.innerHTML = '';
  }
  
  // Format the content
  const currentDate = new Date().toLocaleDateString();
  
  const html = `
    <div class="p-8">
      <div class="flex justify-between items-center mb-6">
        <div>
          <h1 class="text-2xl font-bold">Service History</h1>
          <p class="text-gray-500">Generated: ${currentDate}</p>
        </div>
      </div>
      
      <div class="mb-6">
        <h2 class="text-xl font-semibold mb-2">Vehicle Information</h2>
        <div class="border p-4 rounded-md">
          <p><strong>Make:</strong> ${vehicle.make}</p>
          <p><strong>Model:</strong> ${vehicle.model}</p>
          <p><strong>Year:</strong> ${vehicle.year}</p>
          <p><strong>VIN:</strong> ${vehicle.vin || 'N/A'}</p>
          <p><strong>License Plate:</strong> ${vehicle.plate || 'N/A'}</p>
          <p><strong>Current Mileage:</strong> ${vehicle.mileage} km</p>
        </div>
      </div>
      
      <h2 class="text-xl font-semibold mb-2">Service Records</h2>
      ${serviceLogs
        .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
        .map(log => `
          <div class="border rounded-md mb-6 break-inside-avoid">
            <div class="bg-gray-50 p-3 border-b">
              <h3 class="font-bold">${log.serviceType}</h3>
              <div class="flex justify-between text-sm">
                <span>${new Date(log.date).toLocaleDateString()}</span>
                <span>${log.mileage} km</span>
                ${log.cost ? `<span>${log.cost} kr</span>` : ''}
              </div>
            </div>
            <div class="p-3">
              <p>${log.description}</p>
              
              ${log.parts && log.parts.length > 0 ? `
                <div class="mt-2">
                  <strong>Parts used:</strong> ${log.parts.join(', ')}
                </div>
              ` : ''}
              
              ${log.tasks && log.tasks.length > 0 ? `
                <div class="mt-3">
                  <strong>Service Procedure:</strong>
                  <ol class="mt-2 list-decimal pl-5">
                    ${log.tasks.map(task => `
                      <li class="mb-2">
                        ${task.description}
                        ${task.torqueSpec ? `<div class="text-sm"><strong>Torque:</strong> ${task.torqueSpec}</div>` : ''}
                        ${task.toolsRequired && task.toolsRequired.length > 0 ? 
                          `<div class="text-sm"><strong>Tools:</strong> ${task.toolsRequired.join(', ')}</div>` : ''}
                        ${task.notes ? `<div class="text-sm italic">${task.notes}</div>` : ''}
                      </li>
                    `).join('')}
                  </ol>
                </div>
              ` : ''}
            </div>
          </div>
        `).join('')}
      
      <div class="mt-8 text-center text-sm text-gray-500">
        <p>Generated by Wrench Whisperer</p>
      </div>
    </div>
  `;
  
  printSection.innerHTML = html;
  
  // Trigger print
  window.print();
};
