
import { Vehicle, ServiceLog } from './mockData';

export const printServiceHistory = (vehicle: Vehicle, serviceLogs: ServiceLog[]) => {
  // Create printable section if it doesn't exist
  let printSection = document.querySelector('.print-section');
  
  if (!printSection) {
    printSection = document.createElement('div');
    printSection.classList.add('print-section');
    document.body.appendChild(printSection);
  } else {
    printSection.innerHTML = '';
  }
  
  // Format the content
  const currentDate = new Date().toLocaleDateString();
  
  const html = `
    <div class="p-8">
      <div class="flex justify-between items-center mb-6">
        <div>
          <h1 class="text-2xl font-bold">Service History</h1>
          <p class="text-gray-500">Generated: ${currentDate}</p>
        </div>
      </div>
      
      <div class="mb-6">
        <h2 class="text-xl font-semibold mb-2">Vehicle Information</h2>
        <div class="border p-4 rounded-md">
          <p><strong>Make:</strong> ${vehicle.make}</p>
          <p><strong>Model:</strong> ${vehicle.model}</p>
          <p><strong>Year:</strong> ${vehicle.year}</p>
          <p><strong>VIN:</strong> ${vehicle.vin || 'N/A'}</p>
          <p><strong>License Plate:</strong> ${vehicle.plate || 'N/A'}</p>
          <p><strong>Current Mileage:</strong> ${vehicle.mileage} km</p>
        </div>
      </div>
      
      <h2 class="text-xl font-semibold mb-2">Service Records</h2>
      <table class="w-full border-collapse">
        <thead>
          <tr class="bg-gray-100">
            <th class="border p-2 text-left">Date</th>
            <th class="border p-2 text-left">Mileage (km)</th>
            <th class="border p-2 text-left">Service Type</th>
            <th class="border p-2 text-left">Description</th>
            <th class="border p-2 text-left">Parts</th>
            <th class="border p-2 text-left">Cost (kr)</th>
          </tr>
        </thead>
        <tbody>
          ${serviceLogs
            .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
            .map(log => `
              <tr>
                <td class="border p-2">${new Date(log.date).toLocaleDateString()}</td>
                <td class="border p-2">${log.mileage}</td>
                <td class="border p-2">${log.serviceType}</td>
                <td class="border p-2">${log.description}</td>
                <td class="border p-2">${log.parts ? log.parts.join(', ') : '-'}</td>
                <td class="border p-2">${log.cost ? `${log.cost} kr` : '-'}</td>
              </tr>
            `).join('')}
        </tbody>
      </table>
      
      <div class="mt-8 text-center text-sm text-gray-500">
        <p>Generated by Wrench Whisperer</p>
      </div>
    </div>
  `;
  
  printSection.innerHTML = html;
  
  // Trigger print
  window.print();
};
