// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zahnqwnyoezdnuccryqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphaG5xd255b2V6ZG51Y2NyeXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDg2MzAsImV4cCI6MjA2MTkyNDYzMH0.RimmDL4G41TLtMKpgL-vDceBs-l8s1Waf4ciQjlzjqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);